title: el pasado futuro
author: German Rz
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Cuando nuestro pasado no es más que nuestro futuro, Es una guerra por nuestra libertad desde que fuimos creados

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
